org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neoforge_full_version=21.1.249
neoforge_loader_version=4
neo_version_range=[21.1.199,)
kubejs_version=2101.7.2-build.336

mod_id=directorscamera
mod_name=Director's Camera
mod_version=1.0.1
maven_group=com.breakinblocks
archives_base_name=directorscamera
mod_author=Breakin Blocks
