org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
neoforge_full_version=26.1.2.95
neoforge_loader_version=11
neo_version_range=[26.1.2,)
kubejs_version=26.1.2-8.0.4

mod_id=directorscamera
mod_name=Director's Camera
mod_version=1.0.1
maven_group=com.breakinblocks
archives_base_name=directorscamera
mod_author=Breakin Blocks
